name: Build and push docker image

on:
  push:
    tags:
      - '**'
  workflow_dispatch:


jobs:

  build-and-push-docker-image:

    runs-on: ubuntu-latest
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    env:
      CONTAINERNAME: database
      SCHEMA: live
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      PG_READ_PWD: ${{ secrets.PG_READ_PWD }}
      PG_WRITE_PWD: ${{ secrets.PG_WRITE_PWD }}
      PG_GRETL_PWD: ${{ secrets.PG_GRETL_PWD }}
      ILI2PG_VERSION: 4.9.1

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Install ili2db
        run: |
          curl -o /tmp/ili2pg-$ILI2PG_VERSION.zip https://downloads.interlis.ch/ili2pg/ili2pg-$ILI2PG_VERSION.zip
          mkdir /tmp/ili2pg
          unzip -d /tmp/ili2pg /tmp/ili2pg-${ILI2PG_VERSION}.zip
          chmod -R ogu+rwx /tmp/ili2pg/*

      - name: Start database structure
        run: |
          docker run \
            --name $CONTAINERNAME \
            -d \
            -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
            -e POSTGRES_DB=$POSTGRES_DB \
            -e POSTGRES_HOST_AUTH_METHOD=md5 \
            -e PG_READ_PWD=$PG_READ_PWD \
            -e PG_WRITE_PWD=$PG_WRITE_PWD \
            -e PG_GRETL_PWD=$PG_GRETL_PWD \
            -e SCHEMA=$SCHEMA \
            -p 54321:5432 \
            ghcr.io/openoereb/ch.oereb_base:latest
          until docker exec $CONTAINERNAME pg_isready; do \
            echo "$CONTAINERNAME was not ready, waiting another cycle"; \
            sleep 5; \
          done
      - name: Insert cantonal configuration catalogues
        run: |
          ./scripts/ch.sh.base.build.insert.OeREBKRM_V2_0.sh
      - name: Insert cantonal AV
        run: |
          ./scripts/ch.sh.base.build.insert.av.sh

      - name: Shut down DB container
        run: |
          docker container stop $CONTAINERNAME

      - name: Build Image
        run: |
          docker commit $CONTAINERNAME ghcr.io/${{ github.repository }}:latest
          docker tag ghcr.io/${{ github.repository }}:latest ghcr.io/${{ github.repository }}:${{ github.ref_name }}
      - name: Push image tags
        run: |
          docker push ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:${{ github.ref_name }}
